#!/usr/bin/env bash

set -euo pipefail

# Brewfile hash: {{ include ".AptPackages" | sha256sum }}
sudo apt-get update
packages=$(cat "$(chezmoi source-path)/.AptPackages")
sudo apt-get install -y $packages
