#!/usr/bin/env bash

# make sure path is current
source ~/.zshrc

# extensions file hash: {{ include ".vscode_extensions" | sha256sum }}
cat $(chezmoi source-path)/.vscode_extensions | xargs -L 1 code --install-extension
